#!/usr/bin/env bash
# A //go:generate directive names a command, and go generate runs it --
# nothing else does, go build included. Here the command is a small Go
# program that writes a String method for an order status type, the job the
# stringer tool does outside the standard library. Building before generating
# fails; generating and then building works; the generated file carries the
# header that Go tools recognise.
set -u
export GOTOOLCHAIN=local

dir=$(mktemp -d)
trap 'rm -rf "$dir"' EXIT
cd "$dir" || exit 1

say() { printf '$ %s\n' "$*"; }

go mod init example >/dev/null 2>&1 || exit 1

cat >status.go <<'GO'
package main

//go:generate go run ./gen

// Status is the state of an order. Its String method is in status_string.go,
// which go generate writes.
type Status int

const (
	Pending Status = iota
	Paid
	Shipped
	Cancelled
)
GO

mkdir gen
cat >gen/main.go <<'GO'
// Command gen writes status_string.go: a String method for Status, from the
// names listed here. It stands in for stringer, which lives outside std.
package main

import (
	"fmt"
	"os"
)

func main() {
	names := []string{"Pending", "Paid", "Shipped", "Cancelled"}
	out, err := os.Create("status_string.go")
	if err != nil {
		panic(err)
	}
	defer out.Close()
	fmt.Fprintf(out, "// Code generated by gen from %s:%s; DO NOT EDIT.\n\n", os.Getenv("GOFILE"), os.Getenv("GOLINE"))
	fmt.Fprintf(out, "package %s\n\n", os.Getenv("GOPACKAGE"))
	fmt.Fprintln(out, `import "fmt"`)
	fmt.Fprintln(out)
	fmt.Fprintln(out, "func (s Status) String() string {")
	fmt.Fprintln(out, "\tswitch s {")
	for _, name := range names {
		fmt.Fprintf(out, "\tcase %s:\n\t\treturn %q\n", name, name)
	}
	fmt.Fprintln(out, "\t}")
	fmt.Fprintln(out, `	return fmt.Sprintf("Status(%d)", int(s))`)
	fmt.Fprintln(out, "}")
}
GO

cat >main.go <<'GO'
package main

import "fmt"

func main() {
	for s := Pending; s <= Cancelled+1; s++ {
		fmt.Println(int(s), s.String())
	}
}
GO

say 'gofmt -l .'
gofmt -l .

say 'go build -o orders .'
go build -o orders . 2>&1
echo "exit status $?"

say 'go generate -x ./...'
go generate -x ./... 2>&1
echo "exit status $?"

say 'cat status_string.go'
cat status_string.go

say 'gofmt -l status_string.go'
gofmt -l status_string.go

say 'go build -o orders . && ./orders'
go build -o orders . && ./orders
