// Kata: write the generator itself as one program. It emits a String method
// for a Priority type into a buffer, formats the text with go/format the way
// gofmt would, checks the first line against the regular expression that
// go help generate gives for generated files, and prints the file it would
// have written.
//
//	go build -trimpath go_generate_runs_a_command_kata_go.go && ./go_generate_runs_a_command_kata_go
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"regexp"
)

// generatedHeader is the pattern from go help generate, which gofmt, go vet
// and editors use to recognise a generated file.
var generatedHeader = regexp.MustCompile(`^// Code generated .* DO NOT EDIT\.$`)

func main() {
	names := []string{"Low", "Normal", "Urgent"}

	var src bytes.Buffer
	fmt.Fprintln(&src, "// Code generated by go_generate_runs_a_command_kata_go; DO NOT EDIT.")
	fmt.Fprintln(&src)
	fmt.Fprintln(&src, "package orders")
	fmt.Fprintln(&src)
	fmt.Fprintln(&src, `import "fmt"`)
	fmt.Fprintln(&src)
	fmt.Fprintln(&src, "func (p Priority) String() string {")
	fmt.Fprintln(&src, "switch p {") // unindented on purpose: go/format fixes it
	for _, name := range names {
		fmt.Fprintf(&src, "case %s: return %q\n", name, name)
	}
	fmt.Fprintln(&src, "}")
	fmt.Fprintln(&src, `return fmt.Sprintf("Priority(%d)", int(p))`)
	fmt.Fprintln(&src, "}")

	formatted, err := format.Source(src.Bytes())
	if err != nil {
		panic(err)
	}
	firstLine, _, _ := bytes.Cut(formatted, []byte("\n"))
	fmt.Println("header recognised:", generatedHeader.Match(firstLine))
	fmt.Println("go/format changed the text:", !bytes.Equal(formatted, src.Bytes()))
	fmt.Println("---")
	fmt.Print(string(formatted))
}
